### PR TITLE
newapkbuild: Checksum after adding build-steps

### PR DESCRIPTION
**Pull request by ghost**
The checksum used to be in the middle of APKBUILD files generated with
newapkbuild, because it was checksummed before adding the build-steps.

Discussion: I don't like the fact, that newapkbuild now swallows some abuild errors. So I am open to suggestions.

### CODE REVIEW

**Comment by nmeum** [comment]
I think this is needed but I don't like the fact that all abuild errors caused by `abuild fetch unpack` are ignored now either.

**Comment by ghost** [comment]
@nmeum I added the version which first didn't push, because I thought it's too much magic.

**Comment by ncopa** [comment]
Since 1cbc853155b99aa062b1f30dd4d2c29fb9576e20, i think we only need:
````diff
diff --git a/newapkbuild.in b/newapkbuild.in
index 19f822a..a3e16cf 100644
--- a/newapkbuild.in
+++ b/newapkbuild.in
@@ -339,6 +339,7 @@ __EOF__
 }
 
 __EOF__
+       abuild -f checksum
 }
 
 usage() {
````

**Comment by ncopa** [comment]
fixed with 51830efbb5e6a07f0ec93e6c59c12680b518ca56

**Comment by ghost** [comment]
confirmed

**Pull request closed without merging**
